// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqYfCf4Axjfq9njJMPb3FQuNl0xwJ31SA',
    appId: '1:551002878268:web:f40daa78a6bb6946c02e39',
    messagingSenderId: '551002878268',
    projectId: 'e-commerce-25c28',
    authDomain: 'e-commerce-25c28.firebaseapp.com',
    storageBucket: 'e-commerce-25c28.appspot.com',
    measurementId: 'G-BETGTGNY52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtFAddc_JdWc5okbDbQNYPxrD_BagbT8',
    appId: '1:551002878268:android:609ad65eb043bdaec02e39',
    messagingSenderId: '551002878268',
    projectId: 'e-commerce-25c28',
    storageBucket: 'e-commerce-25c28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19JeuOoAqXHftKUaCiqC78xfS2F5kAg8',
    appId: '1:551002878268:ios:abbc135a2729587dc02e39',
    messagingSenderId: '551002878268',
    projectId: 'e-commerce-25c28',
    storageBucket: 'e-commerce-25c28.appspot.com',
    iosClientId: '551002878268-1j92kvb84ccd2joc98cu3h8bhs1houg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19JeuOoAqXHftKUaCiqC78xfS2F5kAg8',
    appId: '1:551002878268:ios:d5716d452a46a3cec02e39',
    messagingSenderId: '551002878268',
    projectId: 'e-commerce-25c28',
    storageBucket: 'e-commerce-25c28.appspot.com',
    iosClientId: '551002878268-osug6pnkauaqaqfm5uht2hqmu0ot74e7.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
